import os
import time
import requests
import logging
from prometheus_client import start_http_server, Gauge

logging.basicConfig(level=logging.DEBUG, format='[%(asctime)s] %(levelname)s: %(message)s', datefmt='%Y-%m-%d %H:%M:%S')

BATTLELOG_PLAYER_ID = os.environ.get('BATTLELOG_PLAYER_ID')

if BATTLELOG_PLAYER_ID == None:
    raise Exception('BATTLELOG_PLAYER_ID is not defined')

BATTLELOG_GENERAL_STATS_URL = f'https://battlelog.battlefield.com/bf4/warsawdetailedstatspopulate/{BATTLELOG_PLAYER_ID}/1'
BATTLELOG_VEHICLE_STATS_URL = f'https://battlelog.battlefield.com/bf4/warsawvehiclesPopulateStats/{BATTLELOG_PLAYER_ID}/1/stats'

generalStats_skill = Gauge('battlefield_4_generalStats_skill', 'Current skill')
generalStats_timePlayed = Gauge('battlefield_4_generalStats_timePlayed', 'Time played in seconds')
generalStats_rank = Gauge('battlefield_4_generalStats_rank', 'Current rank')
generalStats_scoreTotal = Gauge('battlefield_4_generalStats_scoreTotal', 'Total player score')
generalStats_scoreVehicle = Gauge('battlefield_4_generalStats_scoreVehicle', 'Total vehicle score')
generalStats_scoreUnlock = Gauge('battlefield_4_generalStats_scoreUnlock', 'Total unlock score')
generalStats_scoreAward = Gauge('battlefield_4_generalStats_scoreAward', 'Total award score')
generalStats_scoreSquad = Gauge('battlefield_4_generalStats_scoreSquad', 'Total squad score')
generalStats_scoreAssault = Gauge('battlefield_4_generalStats_scoreAssault', 'Total assault score')
generalStats_scoreEngineer = Gauge('battlefield_4_generalStats_scoreEngineer', 'Total engineer score')
generalStats_scoreSupport = Gauge('battlefield_4_generalStats_scoreSupport', 'Total support score')
generalStats_scoreRecon = Gauge('battlefield_4_generalStats_scoreRecon', 'Total recon score')
generalStats_scoreCommander = Gauge('battlefield_4_generalStats_scoreCommander', 'Total commander score')
generalStats_deaths = Gauge('battlefield_4_generalStats_deaths', 'Number of deaths')
generalStats_kills = Gauge('battlefield_4_generalStats_kills', 'Number of kills')
generalStats_killsAssault = Gauge('battlefield_4_generalStats_killsAssault', 'Number of kills with assault kit')
generalStats_killsRecon = Gauge('battlefield_4_generalStats_killsRecon', 'Number of kills with recon kit')
generalStats_killsSupport = Gauge('battlefield_4_generalStats_killsSupport', 'Number of kills with support kit')
generalStats_killsEngineer = Gauge('battlefield_4_generalStats_killsEngineer', 'Number of kills with engineer kit')
generalStats_avengerKills = Gauge('battlefield_4_generalStats_avengerKills', 'Number of avenger kills')
generalStats_saviorKills = Gauge('battlefield_4_generalStats_saviorKills', 'Number of savior kills')
generalStats_headshots = Gauge('battlefield_4_generalStats_headshots', 'Number of headshots')
generalStats_longestHeadshot = Gauge('battlefield_4_generalStats_longestHeadshot', 'Longest headshot in meters')
generalStats_highestKillStreak = Gauge('battlefield_4_generalStats_highestKillStreak', 'Highest kill streak')
generalStats_killAssists = Gauge('battlefield_4_generalStats_killAssists', 'Number of kill assists')
generalStats_wins = Gauge('battlefield_4_generalStats_wins', 'Number of rounds won')
generalStats_losses = Gauge('battlefield_4_generalStats_losses', 'Number of rounds lost')
generalStats_rounds = Gauge('battlefield_4_generalStats_rounds', 'Numer of rounds played')
generalStats_shotsFired = Gauge('battlefield_4_generalStats_shotsFired', 'Number of shots fired')
generalStats_shotsHit = Gauge('battlefield_4_generalStats_shotsHit', 'Number of shots hit')
generalStats_repairs = Gauge('battlefield_4_generalStats_repairs', 'Number of repairs')
generalStats_resupplies = Gauge('battlefield_4_generalStats_resupplies', 'Number of resupplies')
generalStats_revives = Gauge('battlefield_4_generalStats_revives', 'Number of revives')
generalStats_heals = Gauge('battlefield_4_generalStats_heals', 'Number of heals')
generalStats_suppressionAssists = Gauge('battlefield_4_generalStats_suppressionAssists', 'Number of suppression assists')
generalStats_vehiclesDestroyed = Gauge('battlefield_4_generalStats_vehiclesDestroyed', 'Number of vehicles destroyed')
generalStats_vehicleDamage = Gauge('battlefield_4_generalStats_vehicleDamage', 'Total vehicle damage')
generalStats_flagCaptured = Gauge('battlefield_4_generalStats_flagCaptured', 'Number of flag captured')
generalStats_flagDefend = Gauge('battlefield_4_generalStats_flagDefend', 'Number of flag defend')

vehicleStats_btr90_kills = Gauge('battlefield_4_vehicleStats_btr90_kills', 'Number of kills with BTR-90')
vehicleStats_btr90_timePlayed = Gauge('battlefield_4_vehicleStats_btr90_timePlayer', 'Time played with BTR-90 in seconds')
vehicleStats_mi28havoc_kills = Gauge('battlefield_4_vehicleStats_mi28havoc_kills', 'Number of kills with MI-28 HAVOC')
vehicleStats_mi28havoc_timePlayed = Gauge('battlefield_4_vehicleStats_mi28havoc_timePlayer', 'Time played with MI-28 HAVOC in seconds')
vehicleStats_zbd09_kills = Gauge('battlefield_4_vehicleStats_zbd09_kills', 'Number of kills with ZBD-09')
vehicleStats_zbd09_timePlayed = Gauge('battlefield_4_vehicleStats_zbd09_timePlayer', 'Time played with ZBD-09 in seconds')
vehicleStats_a10warthog_kills = Gauge('battlefield_4_vehicleStats_a10warthog_kills', 'Number of kills with A10 WARTHOG')
vehicleStats_a10warthog_timePlayed = Gauge('battlefield_4_vehicleStats_a10warthog_timePlayer', 'Time played with A10 WARTHOG in seconds')
vehicleStats_z11w_us_kills = Gauge('battlefield_4_vehicleStats_z11w_us_kills', 'Number of kills with Z-11W (US)')
vehicleStats_z11w_us_timePlayed = Gauge('battlefield_4_vehicleStats_z11w_us_timePlayer', 'Time played with Z-11W (US) in seconds')
vehicleStats_z11w_ru_kills = Gauge('battlefield_4_vehicleStats_z11w_ru_kills', 'Number of kills with Z-11W (RU)')
vehicleStats_z11w_ru_timePlayed = Gauge('battlefield_4_vehicleStats_z11w_ru_timePlayer', 'Time played with Z-11W (RU) in seconds')
vehicleStats_t90a_kills = Gauge('battlefield_4_vehicleStats_t90a_kills', 'Number of kills with T-90A')
vehicleStats_t90a_timePlayed = Gauge('battlefield_4_vehicleStats_t90a_timePlayer', 'Time played with T-90A in seconds')
vehicleStats_dv15_us_kills = Gauge('battlefield_4_vehicleStats_dv15_us_kills', 'Number of kills with DV-15 (US)')
vehicleStats_dv15_us_timePlayed = Gauge('battlefield_4_vehicleStats_dv15_us_timePlayer', 'Time played with DV-15 (US) in seconds')
vehicleStats_dv15_ru_kills = Gauge('battlefield_4_vehicleStats_dv15_ru_kills', 'Number of kills with DV-15 (RU)')
vehicleStats_dv15_ru_timePlayed = Gauge('battlefield_4_vehicleStats_dv15_ru_timePlayer', 'Time played with DV-15 (RU) in seconds')
vehicleStats_zfb05_kills = Gauge('battlefield_4_vehicleStats_zfb05_kills', 'Number of kills with ZFB-05')
vehicleStats_zfb05_timePlayed = Gauge('battlefield_4_vehicleStats_zfb05_timePlayer', 'Time played with ZFB-05 in seconds')
vehicleStats_m1161itv_kills = Gauge('battlefield_4_vehicleStats_m1161itv_kills', 'Number of kills with M1161 ITV')
vehicleStats_m1161itv_timePlayed = Gauge('battlefield_4_vehicleStats_m1161itv_timePlayer', 'Time played with M1161 ITV in seconds')
vehicleStats_rawr_kills = Gauge('battlefield_4_vehicleStats_rawr_kills', 'Number of kills with RAWR')
vehicleStats_50cal_kills = Gauge('battlefield_4_vehicleStats_50cal_kills', 'Number of kills with 50 CAL')
vehicleStats_50cal_timePlayed = Gauge('battlefield_4_vehicleStats_50cal_timePlayer', 'Time played with 50 CAL in seconds')
vehicleStats_z10w_kills = Gauge('battlefield_4_vehicleStats_z10w_kills', 'Number of kills with Z-10W')
vehicleStats_z10w_timePlayed = Gauge('battlefield_4_vehicleStats_z10w_timePlayer', 'Time played with Z-10W in seconds')
vehicleStats_launchpod_kills = Gauge('battlefield_4_vehicleStats_launchpod_kills', 'Number of kills with LAUNCH POD')
vehicleStats_launchpod_timePlayed = Gauge('battlefield_4_vehicleStats_launchpod_timePlayer', 'Time played with LAUNCH POD in seconds')
vehicleStats_j20_kills = Gauge('battlefield_4_vehicleStats_j20_kills', 'Number of kills with J-20')
vehicleStats_j20_timePlayed = Gauge('battlefield_4_vehicleStats_j20_timePlayer', 'Time played with J-20 in seconds')
vehicleStats_ucav_kills = Gauge('battlefield_4_vehicleStats_ucav1_kills', 'Number of kills with UCAV')
vehicleStats_spm3_kills = Gauge('battlefield_4_vehicleStats_spm3_kills', 'Number of kills with SPM-3')
vehicleStats_spm3_timePlayed = Gauge('battlefield_4_vehicleStats_spm3_timePlayer', 'Time played with SPM-3 in seconds')
vehicleStats_su25tmfrogfoot_kills = Gauge('battlefield_4_vehicleStats_su25tmfrogfoot_kills', 'Number of kills with SU-25TM FROGFOOT')
vehicleStats_su25tmfrogfoot_timePlayed = Gauge('battlefield_4_vehicleStats_su25tmfrogfoot_timePlayer', 'Time played with SU-25TM FROGFOOT in seconds')
vehicleStats_pwc_kills = Gauge('battlefield_4_vehicleStats_pwc_kills', 'Number of kills with PWC')
vehicleStats_pwc_timePlayed = Gauge('battlefield_4_vehicleStats_pwc_timePlayer', 'Time played with PWC in seconds')
vehicleStats_ah1zviper_kills = Gauge('battlefield_4_vehicleStats_ah1zviper_kills', 'Number of kills with AH-1Z VIPER')
vehicleStats_ah1zviper_timePlayed = Gauge('battlefield_4_vehicleStats_ah1zviper_timePlayer', 'Time played with AH-1Z VIPER in seconds')
vehicleStats_mav_kills = Gauge('battlefield_4_vehicleStats_mav_kills', 'Number of kills with MAV')
vehicleStats_ah6jlittlebird_kills = Gauge('battlefield_4_vehicleStats_ah6jlittlebird_kills', 'Number of kills with AH-6J LITTLE BIRD')
vehicleStats_ah6jlittlebird_timePlayed = Gauge('battlefield_4_vehicleStats_ah6jlittlebird_timePlayer', 'Time played with AH-6J LITTLE BIRD in seconds')
vehicleStats_z9haitun_kills = Gauge('battlefield_4_vehicleStats_z9haitun_kills', 'Number of kills with Z-9 HAITUN')
vehicleStats_z9haitun_timePlayed = Gauge('battlefield_4_vehicleStats_z9haitun_timePlayer', 'Time played with Z-9 HAITUN in seconds')
vehicleStats_acv_kills = Gauge('battlefield_4_vehicleStats_acv_kills', 'Number of kills with ACV')
vehicleStats_acv_timePlayed = Gauge('battlefield_4_vehicleStats_acv_timePlayer', 'Time played with ACV in seconds')
vehicleStats_q5fantan_kills = Gauge('battlefield_4_vehicleStats_q5fantan_kills', 'Number of kills with Q-5 FANTAN')
vehicleStats_q5fantan_timePlayed = Gauge('battlefield_4_vehicleStats_q5fantan_timePlayer', 'Time played with Q-5 FANTAN in seconds')
vehicleStats_9m133kornetlauncher_kills = Gauge('battlefield_4_vehicleStats_9m133kornetlauncher_kills', 'Number of kills with 9M133 KORNET LAUNCHER')
vehicleStats_9m133kornetlauncher_timePlayed = Gauge('battlefield_4_vehicleStats_9m133kornetlauncher_timePlayer', 'Time played with 9M133 KORNET LAUNCHER in seconds')
vehicleStats_dpv_kills = Gauge('battlefield_4_vehicleStats_dpv_kills', 'Number of kills with DPV')
vehicleStats_dpv_timePlayed = Gauge('battlefield_4_vehicleStats_dpv_timePlayer', 'Time played with DPV in seconds')
vehicleStats_suav_kills = Gauge('battlefield_4_vehicleStats_suav_kills', 'Number of kills with SUAV')
vehicleStats_xd1accipiter_kills = Gauge('battlefield_4_vehicleStats_xd1accipiter_kills', 'Number of kills with XD-1 ACCIPITER')
vehicleStats_hj8launcher_kills = Gauge('battlefield_4_vehicleStats_hj8launcher_kills', 'Number of kills with HJ-8 LAUNCHER')
vehicleStats_hj8launcher_timePlayed = Gauge('battlefield_4_vehicleStats_hj8launcher_timePlayer', 'Time played with HJ-8 LAUNCHER in seconds')
vehicleStats_bomber_kills = Gauge('battlefield_4_vehicleStats_bomber_kills', 'Number of kills with BOMBER')
vehicleStats_bomber_timePlayed = Gauge('battlefield_4_vehicleStats_bomber_timePlayer', 'Time played with BOMBER in seconds')
vehicleStats_lav25_kills = Gauge('battlefield_4_vehicleStats_lav25_kills', 'Number of kills with LAV-25')
vehicleStats_lav25_timePlayed = Gauge('battlefield_4_vehicleStats_lav25_timePlayer', 'Time played with LAV-25 in seconds')
vehicleStats_uh1yvenom_kills = Gauge('battlefield_4_vehicleStats_uh1yvenom_kills', 'Number of kills with UH-1Y VENOM')
vehicleStats_uh1yvenom_timePlayed = Gauge('battlefield_4_vehicleStats_uh1yvenom_timePlayer', 'Time played with UH-1Y VENOM in seconds')
vehicleStats_f35_kills = Gauge('battlefield_4_vehicleStats_f35_kills', 'Number of kills with F35')
vehicleStats_f35_timePlayed = Gauge('battlefield_4_vehicleStats_f35_timePlayer', 'Time played with F35 in seconds')
vehicleStats_oldcannon_kills = Gauge('battlefield_4_vehicleStats_oldcannon_kills', 'Number of kills with OLD CANNON')
vehicleStats_oldcannon_timePlayed = Gauge('battlefield_4_vehicleStats_oldcannon_timePlayer', 'Time played with OLD CANNON in seconds')
vehicleStats_type99mbt_kills = Gauge('battlefield_4_vehicleStats_type99mbt_kills', 'Number of kills with TYPE 99-MBT')
vehicleStats_type99mbt_timePlayed = Gauge('battlefield_4_vehicleStats_type99mbt_timePlayer', 'Time played with TYPE 99-MBT in seconds')
vehicleStats_ka60kasatka_kills = Gauge('battlefield_4_vehicleStats_ka60kasatka_kills', 'Number of kills with KA-60 KASATKA')
vehicleStats_ka60kasatka_timePlayed = Gauge('battlefield_4_vehicleStats_ka60kasatka_timePlayer', 'Time played with KA-60 KASATKA in seconds')
vehicleStats_lavad_kills = Gauge('battlefield_4_vehicleStats_lavad_kills', 'Number of kills with LAV-AD')
vehicleStats_lavad_timePlayed = Gauge('battlefield_4_vehicleStats_lavad_timePlayer', 'Time played with LAV-AD in seconds')
vehicleStats_m224mortar_kills = Gauge('battlefield_4_vehicleStats_m224mortar_kills', 'Number of kills with M224 MORTAR')
vehicleStats_m220towlauncher_kills = Gauge('battlefield_4_vehicleStats_m220towlauncher_kills', 'Number of kills with M220 TOW LAUNCHER')
vehicleStats_m220towlauncher_timePlayed = Gauge('battlefield_4_vehicleStats_m220towlauncher_timePlayer', 'Time played with M220 TOW LAUNCHER in seconds')
vehicleStats_m142_kills = Gauge('battlefield_4_vehicleStats_m142_kills', 'Number of kills with M142')
vehicleStats_m142_timePlayed = Gauge('battlefield_4_vehicleStats_m142_timePlayer', 'Time played with M142 in seconds')
vehicleStats_dirtbike_kills = Gauge('battlefield_4_vehicleStats_dirtbike_kills', 'Number of kills with DIRTBIKE')
vehicleStats_dirtbike_timePlayed = Gauge('battlefield_4_vehicleStats_dirtbike_timePlayer', 'Time played with DIRTBIKE in seconds')
vehicleStats_9k22tunguskam_kills = Gauge('battlefield_4_vehicleStats_9k22tunguskam1_kills', 'Number of kills with 9K22 TUNGUSKA-M')
vehicleStats_9k22tunguskam_timePlayed = Gauge('battlefield_4_vehicleStats_9k22tunguskam1_timePlayer', 'Time played with 9K22 TUNGUSKA-M in seconds')
vehicleStats_snowmobile_kills = Gauge('battlefield_4_vehicleStats_snowmobile_kills', 'Number of kills with SNOWMOBILE')
vehicleStats_snowmobile_timePlayed = Gauge('battlefield_4_vehicleStats_snowmobile_timePlayer', 'Time played with SNOWMOBILE in seconds')
vehicleStats_schipunov42_kills = Gauge('battlefield_4_vehicleStats_schipunov42_kills', 'Number of kills with SCHIPUNOV-42')
vehicleStats_schipunov42_timePlayed = Gauge('battlefield_4_vehicleStats_schipunov42_timePlayer', 'Time played with SCHIPUNOV-42 in seconds')
vehicleStats_rhibboat_kills = Gauge('battlefield_4_vehicleStats_rhibboat_kills', 'Number of kills with RHIB BOAT')
vehicleStats_rhibboat_timePlayed = Gauge('battlefield_4_vehicleStats_rhibboat_timePlayer', 'Time played with RHIB BOAT in seconds')
vehicleStats_skidloader_kills = Gauge('battlefield_4_vehicleStats_skidloader_kills', 'Number of kills with SKID LOADER')
vehicleStats_skidloader_timePlayed = Gauge('battlefield_4_vehicleStats_skidloader_timePlayer', 'Time played with SKID LOADER in seconds')
vehicleStats_ac130gunship_kills = Gauge('battlefield_4_vehicleStats_ac130gunship_kills', 'Number of kills with AC-130 GUNSHIP')
vehicleStats_ac130gunship_timePlayed = Gauge('battlefield_4_vehicleStats_ac130gunship_timePlayer', 'Time played with AC-130 GUNSHIP in seconds')
vehicleStats_vdvbuggy_kills = Gauge('battlefield_4_vehicleStats_vdvbuggy_kills', 'Number of kills with VDV BUGGY')
vehicleStats_vdvbuggy_timePlayed = Gauge('battlefield_4_vehicleStats_vdvbuggy_timePlayer', 'Time played with VDV BUGGY in seconds')
vehicleStats_rcb_kills = Gauge('battlefield_4_vehicleStats_rcb_kills', 'Number of kills with RCB')
vehicleStats_rcb_timePlayed = Gauge('battlefield_4_vehicleStats_rcb_timePlayer', 'Time played with RCB in seconds')
vehicleStats_eodbot_kills = Gauge('battlefield_4_vehicleStats_eodbot_kills', 'Number of kills with EOD BOT')
vehicleStats_quadbike_kills = Gauge('battlefield_4_vehicleStats_quadbike_kills', 'Number of kills with QUAD BIKE')
vehicleStats_quadbike_timePlayed = Gauge('battlefield_4_vehicleStats_quadbike_timePlayer', 'Time played with QUAD BIKE in seconds')
vehicleStats_aav7a1amtrac_kills = Gauge('battlefield_4_vehicleStats_aav7a1amtrac_kills', 'Number of kills with AAV-7A1 AMTRAC')
vehicleStats_aav7a1amtrac_timePlayed = Gauge('battlefield_4_vehicleStats_aav7a1amtrac_timePlayer', 'Time played with AAV-7A1 AMTRAC in seconds')
vehicleStats_mrap_kills = Gauge('battlefield_4_vehicleStats_mrap_kills', 'Number of kills with MRAP')
vehicleStats_mrap_timePlayed = Gauge('battlefield_4_vehicleStats_mrap_timePlayer', 'Time played with MRAP in seconds')
vehicleStats_lyt2021_kills = Gauge('battlefield_4_vehicleStats_lyt2021_kills', 'Number of kills with LYT2021')
vehicleStats_lyt2021_timePlayed = Gauge('battlefield_4_vehicleStats_lyt2021_timePlayer', 'Time played with LYT2021 in seconds')
vehicleStats_aamine_kills = Gauge('battlefield_4_vehicleStats_aamine_kills', 'Number of kills with AA MINE')
vehicleStats_m1abrams_kills = Gauge('battlefield_4_vehicleStats_m1abrams_kills', 'Number of kills with M1 ABRAMS')
vehicleStats_m1abrams_timePlayed = Gauge('battlefield_4_vehicleStats_m1abrams_timePlayer', 'Time played with M1 ABRAMS in seconds')
vehicleStats_su50_kills = Gauge('battlefield_4_vehicleStats_su50_kills', 'Number of kills with SU-50')
vehicleStats_su50_timePlayed = Gauge('battlefield_4_vehicleStats_su50_timePlayer', 'Time played with SU-50 in seconds')
vehicleStats_type95aa_kills = Gauge('battlefield_4_vehicleStats_type95aa_kills', 'Number of kills with TYPE 95 AA')
vehicleStats_type95aa_timePlayed = Gauge('battlefield_4_vehicleStats_type95aa_timePlayer', 'Time played with TYPE 95 AA in seconds')
vehicleStats_ht95levkov_kills = Gauge('battlefield_4_vehicleStats_ht95levkov_kills', 'Number of kills with HT-95 LEVKOV')
vehicleStats_ht95levkov_timePlayed = Gauge('battlefield_4_vehicleStats_ht95levkov_timePlayer', 'Time played with HT-95 LEVKOV in seconds')


def main():
    start_http_server(8080)

    while True:
        logging.info('Refreshing metrics...')

        refresh_generalStats_metrics()
        time.sleep(3)
        refresh_vehicleStats_metrics()

        time.sleep(60 * 5)


def refresh_generalStats_metrics():
    logging.debug('Refreshing generalStats metrics...')

    res = requests.get(BATTLELOG_GENERAL_STATS_URL)
    res.raise_for_status()

    data = res.json()['data']['generalStats']

    generalStats_skill.set(int(data['skill']))
    generalStats_timePlayed.set(int(data['timePlayed']))
    generalStats_rank.set(int(data['rank']))
    generalStats_scoreTotal.set(int(data['score']))
    generalStats_scoreVehicle.set(int(data['sc_vehicle']))
    generalStats_scoreUnlock.set(int(data['sc_unlock']))
    generalStats_scoreAward.set(int(data['sc_award']))
    generalStats_scoreSquad.set(int(data['sc_squad']))
    generalStats_scoreAssault.set(int(data['assault']))
    generalStats_scoreEngineer.set(int(data['engineer']))
    generalStats_scoreSupport.set(int(data['support']))
    generalStats_scoreRecon.set(int(data['recon']))
    generalStats_scoreCommander.set(int(data['commander']))
    generalStats_deaths.set(int(data['deaths']))
    generalStats_kills.set(int(data['kills']))
    generalStats_killsAssault.set(int(data['kills_assault']))
    generalStats_killsRecon.set(int(data['kills_recon']))
    generalStats_killsSupport.set(int(data['kills_support']))
    generalStats_killsEngineer.set(int(data['kills_engineer']))
    generalStats_avengerKills.set(int(data['avengerKills']))
    generalStats_saviorKills.set(int(data['saviorKills']))
    generalStats_headshots.set(int(data['headshots']))
    generalStats_longestHeadshot.set(data['longestHeadshot'])
    generalStats_highestKillStreak.set(int(data['killStreakBonus']))
    generalStats_killAssists.set(int(data['killAssists']))
    generalStats_wins.set(int(data['numWins']))
    generalStats_losses.set(int(data['numLosses']))
    generalStats_rounds.set(int(data['numRounds']))
    generalStats_shotsFired.set(int(data['shotsFired']))
    generalStats_shotsHit.set(int(data['shotsHit']))
    generalStats_repairs.set(int(data['repairs']))
    generalStats_resupplies.set(int(data['resupplies']))
    generalStats_revives.set(int(data['revives']))
    generalStats_heals.set(int(data['heals']))
    generalStats_suppressionAssists.set(int(data['suppressionAssists']))
    generalStats_vehiclesDestroyed.set(int(data['vehiclesDestroyed']))
    generalStats_vehicleDamage.set(int(data['vehicleDamage']))
    generalStats_flagCaptured.set(int(data['flagCaptures']))
    generalStats_flagDefend.set(int(data['flagDefend']))


def refresh_vehicleStats_metrics():
    logging.debug('Refreshing vehicleStats metrics...')

    res = requests.get(BATTLELOG_VEHICLE_STATS_URL)
    res.raise_for_status()

    data = parse_vehicle_stats(res.json()['data']['mainVehicleStats'])

    vehicleStats_btr90_kills.set(data['btr-90']['kills'])
    vehicleStats_btr90_timePlayed.set(data['btr-90']['timeIn'])
    vehicleStats_mi28havoc_kills.set(data['mi-28-havoc']['kills'])
    vehicleStats_mi28havoc_timePlayed.set(data['mi-28-havoc']['timeIn'])
    vehicleStats_zbd09_kills.set(data['zbd-09']['kills'])
    vehicleStats_zbd09_timePlayed.set(data['zbd-09']['timeIn'])
    vehicleStats_a10warthog_kills.set(data['a10-warthog']['kills'])
    vehicleStats_a10warthog_timePlayed.set(data['a10-warthog']['timeIn'])
    vehicleStats_z11w_us_kills.set(data['z-11w']['kills'])
    vehicleStats_z11w_us_timePlayed.set(data['z-11w']['timeIn'])
    vehicleStats_z11w_ru_kills.set(data['z-11w2']['kills'])
    vehicleStats_z11w_ru_timePlayed.set(data['z-11w2']['timeIn'])
    vehicleStats_t90a_kills.set(data['t-90a']['kills'])
    vehicleStats_t90a_timePlayed.set(data['t-90a']['timeIn'])
    vehicleStats_dv15_ru_kills.set(data['dv-15']['kills'])
    vehicleStats_dv15_ru_timePlayed.set(data['dv-15']['timeIn'])
    vehicleStats_dv15_us_kills.set(data['dv-151']['kills'])
    vehicleStats_dv15_us_timePlayed.set(data['dv-151']['timeIn'])
    vehicleStats_zfb05_kills.set(data['zfb-05']['kills'])
    vehicleStats_zfb05_timePlayed.set(data['zfb-05']['timeIn'])
    vehicleStats_m1161itv_kills.set(data['m1161-itv']['kills'])
    vehicleStats_m1161itv_timePlayed.set(data['m1161-itv']['timeIn'])
    vehicleStats_rawr_kills.set(data['rawr']['kills'])
    vehicleStats_50cal_kills.set(data['50-cal']['kills'])
    vehicleStats_50cal_timePlayed.set(data['50-cal']['timeIn'])
    vehicleStats_z10w_kills.set(data['z-10w']['kills'])
    vehicleStats_z10w_timePlayed.set(data['z-10w']['timeIn'])
    vehicleStats_launchpod_kills.set(data['launch-pod']['kills'])
    vehicleStats_launchpod_timePlayed.set(data['launch-pod']['timeIn'])
    vehicleStats_j20_kills.set(data['j-20']['kills'])
    vehicleStats_j20_timePlayed.set(data['j-20']['timeIn'])
    vehicleStats_ucav_kills.set(data['ucav1']['kills'])
    vehicleStats_spm3_kills.set(data['spm-3']['kills'])
    vehicleStats_spm3_timePlayed.set(data['spm-3']['timeIn'])
    vehicleStats_su25tmfrogfoot_kills.set(data['su-25tm-frogfoot']['kills'])
    vehicleStats_su25tmfrogfoot_timePlayed.set(data['su-25tm-frogfoot']['timeIn'])
    vehicleStats_pwc_kills.set(data['pwc']['kills'])
    vehicleStats_pwc_timePlayed.set(data['pwc']['timeIn'])
    vehicleStats_ah1zviper_kills.set(data['ah-1z-viper']['kills'])
    vehicleStats_ah1zviper_timePlayed.set(data['ah-1z-viper']['timeIn'])
    vehicleStats_mav_kills.set(data['mav']['kills'])
    vehicleStats_ah6jlittlebird_kills.set(data['ah-6j-little-bird1']['kills'])
    vehicleStats_ah6jlittlebird_timePlayed.set(data['ah-6j-little-bird1']['timeIn'])
    vehicleStats_z9haitun_kills.set(data['z-9-haitun']['kills'])
    vehicleStats_z9haitun_timePlayed.set(data['z-9-haitun']['timeIn'])
    vehicleStats_acv_kills.set(data['acv']['kills'])
    vehicleStats_acv_timePlayed.set(data['acv']['timeIn'])
    vehicleStats_q5fantan_kills.set(data['q-5-fantan']['kills'])
    vehicleStats_q5fantan_timePlayed.set(data['q-5-fantan']['timeIn'])
    vehicleStats_9m133kornetlauncher_kills.set(data['9m133-kornet-launcher']['kills'])
    vehicleStats_9m133kornetlauncher_timePlayed.set(data['9m133-kornet-launcher']['timeIn'])
    vehicleStats_dpv_kills.set(data['dpv']['kills'])
    vehicleStats_dpv_timePlayed.set(data['dpv']['timeIn'])
    vehicleStats_suav_kills.set(data['suav']['kills'])
    vehicleStats_xd1accipiter_kills.set(data['xd-1-accipiter']['kills'])
    vehicleStats_hj8launcher_kills.set(data['hj-8-launcher1']['kills'])
    vehicleStats_hj8launcher_timePlayed.set(data['hj-8-launcher1']['timeIn'])
    vehicleStats_bomber_kills.set(data['bomber']['kills'])
    vehicleStats_bomber_timePlayed.set(data['bomber']['timeIn'])
    vehicleStats_lav25_kills.set(data['lav-25']['kills'])
    vehicleStats_lav25_timePlayed.set(data['lav-25']['timeIn'])
    vehicleStats_uh1yvenom_kills.set(data['uh-1y-venom1']['kills'])
    vehicleStats_uh1yvenom_timePlayed.set(data['uh-1y-venom1']['timeIn'])
    vehicleStats_f35_kills.set(data['f35']['kills'])
    vehicleStats_f35_timePlayed.set(data['f35']['timeIn'])
    vehicleStats_oldcannon_kills.set(data['old-cannon']['kills'])
    vehicleStats_oldcannon_timePlayed.set(data['old-cannon']['timeIn'])
    vehicleStats_type99mbt_kills.set(data['type-99-mbt']['kills'])
    vehicleStats_type99mbt_timePlayed.set(data['type-99-mbt']['timeIn'])
    vehicleStats_ka60kasatka_kills.set(data['ka-60-kasatka1']['kills'])
    vehicleStats_ka60kasatka_timePlayed.set(data['ka-60-kasatka1']['timeIn'])
    vehicleStats_lavad_kills.set(data['lav-ad']['kills'])
    vehicleStats_lavad_timePlayed.set(data['lav-ad']['timeIn'])
    vehicleStats_m224mortar_kills.set(data['m224-mortar1']['kills'])
    vehicleStats_m220towlauncher_kills.set(data['m220-tow-launcher']['kills'])
    vehicleStats_m220towlauncher_timePlayed.set(data['m220-tow-launcher']['timeIn'])
    vehicleStats_m142_kills.set(data['m1421']['kills'])
    vehicleStats_m142_timePlayed.set(data['m1421']['timeIn'])
    vehicleStats_dirtbike_kills.set(data['dirtbike']['kills'])
    vehicleStats_dirtbike_timePlayed.set(data['dirtbike']['timeIn'])
    vehicleStats_9k22tunguskam_kills.set(data['9k22-tunguska-m1']['kills'])
    vehicleStats_9k22tunguskam_timePlayed.set(data['9k22-tunguska-m1']['timeIn'])
    vehicleStats_snowmobile_kills.set(data['snowmobile']['kills'])
    vehicleStats_snowmobile_timePlayed.set(data['snowmobile']['timeIn'])
    vehicleStats_schipunov42_kills.set(data['schipunov-42']['kills'])
    vehicleStats_schipunov42_timePlayed.set(data['schipunov-42']['timeIn'])
    vehicleStats_rhibboat_kills.set(data['rhib-boat']['kills'])
    vehicleStats_rhibboat_timePlayed.set(data['rhib-boat']['timeIn'])
    vehicleStats_skidloader_kills.set(data['skid-loader']['kills'])
    vehicleStats_skidloader_timePlayed.set(data['skid-loader']['timeIn'])
    vehicleStats_ac130gunship_kills.set(data['ac-130-gunship']['kills'])
    vehicleStats_ac130gunship_timePlayed.set(data['ac-130-gunship']['timeIn'])
    vehicleStats_vdvbuggy_kills.set(data['vdv-buggy']['kills'])
    vehicleStats_vdvbuggy_timePlayed.set(data['vdv-buggy']['timeIn'])
    vehicleStats_rcb_kills.set(data['rcb']['kills'])
    vehicleStats_rcb_timePlayed.set(data['rcb']['timeIn'])
    vehicleStats_eodbot_kills.set(data['eod-bot1']['kills'])
    vehicleStats_quadbike_kills.set(data['quad-bike']['kills'])
    vehicleStats_quadbike_timePlayed.set(data['quad-bike']['timeIn'])
    vehicleStats_aav7a1amtrac_kills.set(data['aav-7a1-amtrac']['kills'])
    vehicleStats_aav7a1amtrac_timePlayed.set(data['aav-7a1-amtrac']['timeIn'])
    vehicleStats_mrap_kills.set(data['mrap']['kills'])
    vehicleStats_mrap_timePlayed.set(data['mrap']['timeIn'])
    vehicleStats_lyt2021_kills.set(data['lyt2021']['kills'])
    vehicleStats_lyt2021_timePlayed.set(data['lyt2021']['timeIn'])
    vehicleStats_aamine_kills.set(data['aa-mine1']['kills'])
    vehicleStats_m1abrams_kills.set(data['m1-abrams']['kills'])
    vehicleStats_m1abrams_timePlayed.set(data['m1-abrams']['timeIn'])
    vehicleStats_su50_kills.set(data['su-50']['kills'])
    vehicleStats_su50_timePlayed.set(data['su-50']['timeIn'])
    vehicleStats_type95aa_kills.set(data['type-95-aa']['kills'])
    vehicleStats_type95aa_timePlayed.set(data['type-95-aa']['timeIn'])
    vehicleStats_ht95levkov_kills.set(data['ht-95-levkov']['kills'])
    vehicleStats_ht95levkov_timePlayed.set(data['ht-95-levkov']['timeIn'])


def parse_vehicle_stats(data):
    return { vehicle['slug']: vehicle for vehicle in data }


if __name__ == '__main__':
    print('Application started.')
    main()
